- name: Clean up dev workspace
  hosts: localhost
  become: yes
  tasks:
    - name: Remove config
      ansible.builtin.shell:
        rm -rf /home/kylehipz/dots
        rm -rf /home/kylehipz/ssh-key
        rm -rf /home/kylehipz/.ssh/id_ed25519
        rm -rf /home/kylehipz/.ssh/id_ed25519.pub
        rm -rf /home/kylehipz/.config/nvim
        rm -rf /home/kylehipz/.zshrc
        rm -rf /home/kylehipz/.tmux.conf
